### ISSUE TITLE
デプロイに失敗している

### ISSUE THREAD

**Issue by daybreaksnow** [daybreaksnow/BookRental#21]
/opt/glassfish4/glassfish/domains/domain1/autodeploy/にBookRental.war_deployFailedができている。
こけた時のログを見たい。
また、おそらくデータベース接続周りが原因ではないかと思われる

**Comment by daybreaksnow** [comment]
ログは以下に出来ている
/opt/glassfish4/glassfish/domains/domain1/logs/server.log

参考
http://shogorobe.hatenablog.com/entry/2014/02/10/161921

**Comment by daybreaksnow** [comment]
価値がありそうなログは以下
- JDBCドライバがない？
  <pre>
  [2015-12-10T23:53:34.022+0900] [glassfish 4.1] [WARNING] [poolmgr.create_resource_error] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.resource.allocator] [tid: _ThreadID=60 _ThreadName=AutoDeployer] [timeMillis: 1449759214022] [levelValue: 900] [[
  RAR5038:Unexpected exception while creating resource for pool { PoolInfo : (name=java:app/post-gre-sql_book_rental_snowPool), (applicationName=BookRental) }. Exception : javax.resource.ResourceException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource]]
  [2015-12-10T23:53:34.023+0900] [glassfish 4.1] [WARNING] [poolmgr.get_connection_failure] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=60 _ThreadName=AutoDeployer] [timeMillis: 1449759214023] [levelValue: 900] [[
  RAR5117 : Failed to obtain/create connection from connection pool [ { PoolInfo : (name=java:app/post-gre-sql_book_rental_snowPool), (applicationName=BookRental) } ]. Reason : com.sun.appserv.connectors.internal.api.PoolingException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource]]
  [2015-12-10T23:53:34.032+0900] [glassfish 4.1] [WARNING] [jdbc.exc_get_conn] [javax.enterprise.resource.resourceadapter.com.sun.gjc.spi] [tid: _ThreadID=60 _ThreadName=AutoDeployer] [timeMillis: 1449759214032] [levelValue: 900] [[
  RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource]]]
  [2015-12-10T23:53:34.037+0900] [glassfish 4.1] [SEVERE] [] [org.eclipse.persistence.session./file:/opt/glassfish4/glassfish/domains/domain1/applications/BookRental/WEB-INF/classes/_BookRentalPU.ejb] [tid: _ThreadID=60 _ThreadName=AutoDeployer] [timeMillis: 1449759214037] [levelValue: 1000] [[
  Local Exception Stack: 
  Exception [EclipseLink-4002](Eclipse Persistence Services - 2.6.1.v20150605-31e8258): org.eclipse.persistence.exceptions.DatabaseException
  Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  Error Code: 0
  at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316)
  at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:147)
  at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
  at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:207)
  at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:750)
  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:265)
  at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:731)
  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
  at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:451)
  at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
  at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:492)
  at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:398)
  at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
  at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:487)
  at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
  at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:356)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:356)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
  at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
  at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
  at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
  at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
  at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
  at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
  at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
  at java.util.TimerThread.mainLoop(Timer.java:555)
  at java.util.TimerThread.run(Timer.java:505)
  Caused by: java.sql.SQLException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:121)
  at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135)
  ... 38 more
  Caused by: javax.resource.spi.ResourceAllocationException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:319)
  at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:196)
  at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:171)
  at com.sun.enterprise.connectors.ConnectionManagerImpl.allocateConnection(ConnectionManagerImpl.java:166)
  at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:114)
  ... 39 more
  Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:103)
  at com.sun.enterprise.resource.pool.ConnectionPool.addResource(ConnectionPool.java:282)
  at com.sun.enterprise.resource.pool.ConnectionPool.createResourceAndAddToPool(ConnectionPool.java:1512)
  at com.sun.enterprise.resource.pool.ConnectionPool.createResources(ConnectionPool.java:944)
  at com.sun.enterprise.resource.pool.ConnectionPool.initPool(ConnectionPool.java:230)
  at com.sun.enterprise.resource.pool.ConnectionPool.internalGetResource(ConnectionPool.java:511)
  at com.sun.enterprise.resource.pool.ConnectionPool.getResource(ConnectionPool.java:381)
  at com.sun.enterprise.resource.pool.PoolManagerImpl.getResourceFromPool(PoolManagerImpl.java:245)
  at com.sun.enterprise.resource.pool.PoolManagerImpl.getResource(PoolManagerImpl.java:170)
  at com.sun.enterprise.connectors.ConnectionManagerImpl.getResource(ConnectionManagerImpl.java:360)
  at com.sun.enterprise.connectors.ConnectionManagerImpl.internalGetConnection(ConnectionManagerImpl.java:307)
  ... 43 more
  Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:924)
  at com.sun.enterprise.resource.pool.ConnectionPool.createResource(ConnectionPool.java:1189)
  at com.sun.enterprise.resource.pool.datastructure.RWLockDataStructure.addResource(RWLockDataStructure.java:98)
  ... 53 more
  Caused by: com.sun.appserv.connectors.internal.api.PoolingException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:110)
  at com.sun.enterprise.resource.pool.ConnectionPool.createSingleResource(ConnectionPool.java:907)
  ... 55 more
  Caused by: javax.resource.ResourceException: Class name is wrong or classpath is not set for : org.postgresql.ds.PGSimpleDataSource
  at com.sun.gjc.common.DataSourceObjectBuilder.getDataSourceObject(DataSourceObjectBuilder.java:292)
  at com.sun.gjc.common.DataSourceObjectBuilder.constructDataSourceObject(DataSourceObjectBuilder.java:114)
  at com.sun.gjc.spi.ManagedConnectionFactoryImpl.getDataSource(ManagedConnectionFactoryImpl.java:1300)
  at com.sun.gjc.spi.DSManagedConnectionFactory.getDataSource(DSManagedConnectionFactory.java:163)
  at com.sun.gjc.spi.DSManagedConnectionFactory.createManagedConnection(DSManagedConnectionFactory.java:102)
  at com.sun.enterprise.resource.allocator.LocalTxConnectorAllocator.createResource(LocalTxConnectorAllocator.java:87)
  ... 56 more
  ]]
  </pre>

**Comment by daybreaksnow** [comment]
以下にJDBCドライバをおいてデプロイしなおしたところ動いた。
/opt/glassfish4/glassfish/domains/domain1/lib/

なお、autodeployにwarをおいたままだと何故かglassfishを再起動してもデプロイされないようだったので、asadminのdelpoyを行った
/opt/glassfish4/bin/asadmin deploy BookRental.war
