### ISSUE TITLE
JPAの自動テストを書く

### ISSUE THREAD

**Issue by daybreaksnow** [daybreaksnow/BookRental#23]
DAO、バッキングビーンをテストする

参考
http://kokuzawa.github.io/blog/2013/11/03/unit-test-of-jpa/
http://d.hatena.ne.jp/m-prog/20120404/1333473319

**Comment by daybreaksnow** [comment]
デフォルトではJUnitがライブラリとして使われていない。JUnitクラス作成を選ぶと自動でライブラリが設定されるようだ
https://netbeans.org/kb/docs/java/junit-intro_ja.html

**Comment by daybreaksnow** [comment]
参考サイトの通り以下のpersistence.xmlを作成し、test/META-INFに置き、テストコードを書いたがEntityManagerを作成できない。

・persisitence.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
<persistence-unit name="BookRentalTestPU" transaction-type="RESOURCE_LOCAL">
    <provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
    <class>entity.BrBook</class>
    <class>entity.BrUser</class>
    <class>entity.BrRental</class>
    <properties>
        <property name="javax.persistence.jdbc.driver" value="org.postgresql.Driver"/>
        <property name="javax.persistence.jdbc.url" value="jdbc:postgresql://www.hoge.ne.jp:5432/book_rental"/>
        <property name="javax.persistence.jdbc.user" value="hoge"/>
        <property name="javax.persistence.jdbc.password" value="piyo"/>
    </properties>
</persistence-unit>
</persistence>
```

・ テストコード

```
@Before
public void setUp() throws Exception {
    em = Persistence.createEntityManagerFactory("BookRentalTestPU").createEntityManager();
    userDao = new UserDao();
    userDao.setEntityManager(em);
    bean.setDao(userDao);
}
```

・発生するエラー

```
No Persistence provider for EntityManager named BookRentalTestPU
javax.persistence.PersistenceException: No Persistence provider for EntityManager named BookRentalTestPU
at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:85)
at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
at beans.RegisterUserBeanTest.setUp(RegisterUserBeanTest.java:27)
```

この状態だと構成ファイルにpersisitence.xmlが含まれないので、test_persistence.xmlに名前を変えてsrc/conf(オリジナルのpersisitence.xmlがある場所)に置いてみると、構成ファイルには表示された。
しかし、読込時に同じエラーとなる
